version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.18
    commands:
      - echo "Installing dependencies..."
      - go mod download

  build:
    commands:
      - echo "Building the Go application..."
      - go build -o cmd/main

  post_build:
    commands:
      - echo "Creating deployment package..."
      - zip deployment.zip main
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name reminder-serverless-app-todos --zip-file fileb://deployment.zip

artifacts:
  files:
    - deployment.zip
