version: 0.2

phases:
  install:
    runtime-versions:
      go: 1.20
  build:
    commands:
      - echo Build started on `date`
      - GOOS=linux go build -o main main.go
      - zip -r function.zip main
  post_build:
    commands:
      - aws lambda update-function-code --function-name <your-function-name> --zip-file fileb://function.zip
      - echo Build completed on `date`
